[package]
name = "{{project-name}}"
version = "0.1.0"
authors = ["{{authors}}"]
edition = "2021"
description = "{{project-description}}"
license = "MIT"

[dependencies]
esp-backtrace = { version = "0.15.0", features = [
    "esp32",
    "exception-handler",
    "panic-handler",
    "println",
] }
esp-hal = { version = "0.23.0", features = [ "esp32" ] }
esp-println = { version = "0.13.0", features = ["esp32", "log"] }
log = { version = "0.4.22" }
ssd1306 = "0.10.0"
embedded-graphics = "0.8.0"



[profile.dev]
opt-level = "s"

[profile.release]
codegen-units = 1 # LLVM can perform better optimizations using a single thread
debug = 2
debug-assertions = false
incremental = false
lto = 'fat'
opt-level = 's'
overflow-checks = false
